### ISSUE TITLE
Getting error while simulating

### ISSUE THREAD

**Issue by M-Sree-Harsha** [FOSSEE/Chemical-Simulator-GUI#12]
I am getting error when I am adding a new unit operation to the simulator.

**Comment by nayakpriyam** [comment]
@M-Sree-Harsha Please provide necessary screenshot of the error that you are getting and mention what unit operation you were trying to drag when you got this error.

**Comment by M-Sree-Harsha** [comment]
![error](https://user-images.githubusercontent.com/23764870/114168634-2740f780-994e-11eb-813b-75a16cdf8729.PNG)
the error i am getting

**Comment by M-Sree-Harsha** [comment]
[error.zip](https://github.com/FOSSEE/Chemical-Simulator-GUI/files/6285164/error.zip)
adding .zip file

**Comment by M-Sree-Harsha** [comment]
Issue is resolved with the latest commit
